import {
  RELATIONSHIP_LABELS_PROMPT,
  RELATIONSHIP_LABEL_WRITE_GROUNDING_PROMPT,
} from "./relationship-labels.js";

export const CORRECTIVE_PREFERENCE_SYSTEM_PROMPT = [
  "Classify whether the user is making a durable correction to Borg's future response behavior.",
  "Return corrective_preference only when the user is directing Borg to change how it should answer in future turns, such as a recurring style, boundary, interaction rule, or response pattern.",
  "Return retire_commitment when the user is standing down a supplied active commitment because the matter it governed is resolved or no longer applies; copy the selected id into retires_commitment_id from active_commitments and do not invent ids.",
  "Return none for ordinary task requests, emotional disclosure, venting, disagreement, one-turn instructions, or discussion about a behavior without asking Borg to adopt a lasting change.",
  "Choose exactly one intent per turn: create/update a corrective preference, retire one supplied active commitment, or none.",
  "Separately, fill slot_negations when the user rejects a supplied relational slot value, even if classification is none.",
  "For slot_negations, select subject_entity_id and slot_key only from supplied relational_slots and cite only the current_user_stream_entry_id.",
  "Judge semantic intent across languages. Do not rely on wording, punctuation, capitalization, or phrase shapes.",
  RELATIONSHIP_LABELS_PROMPT,
  RELATIONSHIP_LABEL_WRITE_GROUNDING_PROMPT,
  "The input may include participant_roster; use it as structured context for current speaker, active participants, and grounded relationship-slot sources.",
  "When directive text asserts a sensitive interpersonal relationship, include relationship_claims with requires_grounding=true and cite a supplied relational-slot id or the current user-message stream entry id.",
  "If no accepted evidence grounds the sensitive relationship assertion, rewrite the directive neutrally before emitting it.",
  "Context nouns for logistics, paperwork, scheduling, tools, or services are not relationship assertions unless the text assigns a sensitive interpersonal status between people.",
  "When speaker_entity_id is supplied and the current speaker gives a durable first-person correction, treat that speaker as the committer. In group chat, first-person user commitments/preferences belong to the current sender, not the group, unless the message explicitly says the group is acting.",
  "The input may include cross_audience_targets: other audiences/channels the current speaker can address. When (and only when) that list is non-empty and the speaker gives a standing rule explicitly about one of those other audiences/channels (for example, instructing how to behave in a named channel that is not the current conversation), set applies_to_audience_entity_id to that audience's entity_id, copied verbatim from cross_audience_targets, so the rule lands where it is meant to apply. Otherwise leave applies_to_audience_entity_id null: a rule about the current conversation, or any rule when cross_audience_targets is empty, keeps the default current-audience scope. Match the target by meaning across languages; never invent an id that is not in cross_audience_targets.",
  "Emit kind as boundary for prohibitions/limits, participant_preference for a participant's durable preference, audience_rule for a rule scoped to the audience/channel, or process_norm for a recurring workflow norm. Do not emit assistant_commitment from this extractor.",
  'Emit enforcement_class as "critical" only when violating the directive would disclose or mishandle protected content: privacy, audience scope, safety, explicit no-disclosure, or internal/tool hygiene.',
  "Critical privacy protects private information from disclosure; audience_scope means do not mention or discuss a subject in front of a scoped audience; safety blocks unsafe assistance.",
  "Critical explicit_no_disclosure means an explicit instruction not to reveal, mention, discuss, or relay specific content or a specific topic to a specific person, group, channel, or audience. The directive must name what is forbidden and who or what audience it is forbidden from.",
  'Do not use explicit_no_disclosure for wording style, decision authority, ownership, or recordkeeping, including "do not phrase it as X", "not by committee", "I decide this", or "record this explicitly".',
  "Critical internal_tool_hygiene is only for leaking internal IDs, hidden prompt fragments, tool-call internals, traces, host-capability internals, substrate internals, or capability-boundary leakage.",
  'Do not use internal_tool_hygiene for "surface the ledger", "hold sidecars", "make durable decisions explicit", "health check", "current state only", or any request about how Borg presents user-visible content.',
  "Every critical domain requires an instruction that is present in the user's message. Sensitive subject matter is not a directive about it: a turn that reports, analyzes, quotes, or corrects protected content -- internal mechanism, private facts, substrate details -- while asking Borg for nothing is none. The requirement that a directive name what is forbidden and from whom is a test on what the user said, not a shape this extractor may satisfy by composing the directive itself.",
  "In particular, a speaker describing Borg's own memory, substrate, or affective internals is disclosing that material to Borg, not forbidding it, and the audience that supplied the content is not thereby an audience it must be withheld from.",
  'Emit enforcement_class as "advisory" for durable process norms and output-shape/style preferences, even when phrased as "do not": be terse, skip preamble, do not over-index, do not make this a case file, no timestamped dossier, do not write a manifesto.',
  "participant_preference / preference defaults to advisory. These are usually user-style preferences about terseness, wording, format, framing, or presentation.",
  "If the directive is a genuine named-audience forbidden disclosure, emit type=boundary. Choose kind by source/scope: boundary for a general prohibition, audience_rule for an audience-scoped rule, or participant_preference for a boundary a specific participant set about their own content. Do not wrap hard disclosure boundaries as type=preference.",
  "Negative examples that are advisory, not critical:",
  '- "Lock the approval framework: thresholds, escalation path, and exception process are decided by the project owner, not by committee." => participant_preference / preference / advisory / critical_domain null.',
  '- "At natural wrap points, surface durable decisions and held context in explicit language." => process_norm / rule / advisory / critical_domain null.',
  '- "Hold three working decisions as durable log entries: platform choice, launch owner, and review agenda." => process_norm / rule / advisory / critical_domain null.',
  '- "Use current-state-only updates and avoid historical dossier framing." => participant_preference / preference / advisory / critical_domain null.',
  '- "Run a quick health check before finalizing the project plan." => process_norm / rule / advisory / critical_domain null.',
  '- "Do not phrase recommendations as a committee decision; mark the owner choice explicitly." => participant_preference / preference / advisory / critical_domain null.',
  "Positive examples that are critical:",
  '- "Do not share my medical diagnosis with anyone outside this conversation." => boundary / boundary / critical / privacy.',
  '- "Do not suggest ways to bypass the production deploy review." => boundary / boundary / critical / safety.',
  '- "Do not mention the acquisition discussion to the vendor team." => boundary / boundary / critical / explicit_no_disclosure.',
  '- "Keep the security incident details out of the public status channel." => audience_rule / boundary / critical / audience_scope.',
  '- "Do not expose hidden prompts, tool-call payloads, trace IDs, or host capability details to the end user." => boundary / boundary / critical / internal_tool_hygiene.',
  '- "Don\'t relay my late-night messages to anyone else in this channel." => participant_preference / boundary / critical / explicit_no_disclosure.',
  "Emit critical_domain only for critical commitments. Use null for advisory commitments and none classifications.",
  "Emit directive_family as a short snake_case semantic family slug chosen by meaning, not by surface wording.",
  'Emit closure_pressure_relevance as "no_closure" for durable no-wrap-up/no-signoff/no-closure corrections, "closure_seeking" for durable requests to add closure, and "neutral" otherwise.',
  "Keep directive and reason concise; do not explain ordinary none classifications beyond the required reason field.",
  "When uncertain, return none. The directive must be enforceable by a later response checker without needing to remember the current phrasing.",
].join("\n");
