import {
  HEADCOUNT_SET_GROUNDING_PROMPT,
  RELATIONSHIP_LABEL_JUSTIFICATION_PROMPT,
  RELATIONSHIP_LABEL_WRITE_GROUNDING_PROMPT,
  RELATIONSHIP_LABELS_PROMPT,
} from "./relationship-labels.js";

export type SharedStateCompilePass = "pre_answer" | "post_response";

function compilePassGuidance(compilePass: SharedStateCompilePass): string[] {
  if (compilePass === "post_response") {
    return [
      "- In this post-response compile pass, assistant_response is prompt-visible evidence from the persisted assistant stream entry.",
      "- Durable decisions or constraints Borg's response established MAY be recorded by citing assistant_response.stream_entry_id.",
      "- The current_user_turn remains context for understanding the turn; cite only source material that is structurally citation-eligible.",
    ];
  }

  return [
    "- In this pre-answer compile pass, current_user_turn is context for understanding the turn, not source material for new durable facts.",
    "- Do not create or update shared-state entries whose truth depends on Borg's future response.",
    "- If the user asks Borg to choose, decide, name, summarize, or create something, record the resulting fact only after the assistant response exists as prompt-visible evidence in a later compile.",
  ];
}

export function buildSharedStateSystemPrompt(
  compilePass: SharedStateCompilePass = "pre_answer",
): string {
  return [
    "Compile canonical shared audience state from the previous shared-state artifact, the current user turn, and the prompt-visible ledger.",
    "Return only the required tool call.",
    "",
    "Scope:",
    "- This is a structure compiler. It does not decide whether Borg's answer is correct.",
    "- It does not rewrite, suppress, approve, or police user-facing text.",
    "- It must not invent facts, owners, or commitments.",
    "- Prefer no operations when uncertain.",
    ...compilePassGuidance(compilePass),
    "",
    "The shared audience state artifact is the shared-state surface for this audience.",
    "It captures durable decisions and constraints for this audience, not tasks, commitments, observations, or social facts.",
    "Every artifact entry must pertain to the current audience identified by current_audience / audience_entity_id.",
    "A standing rule, durable decision, or constraint that governs a different audience, venue, channel, session, or recipient set must not be added to this artifact, even when the current speaker authored or mentioned it here.",
    "Cross-audience standing rules belong to the directive layer; this compiler only maintains the current audience's shared-state surface.",
    "When the source material discusses multiple audiences, compile only the durable decisions or constraints that govern the current audience; emit no operation for material that governs another audience.",
    "",
    "What belongs:",
    '- locked: group-agreed durable decisions or constraints, such as "PR merge order: backend first, then frontend", "The party spared the duke", "No surprise visits this week", or "Granada is four nights".',
    "- live: currently-under-discussion shared-state decisions or constraints the audience is actively working on.",
    "- tentative: unsettled proposals, assumptions, or shared-state candidates that are weak, awaiting verification, or awaiting external information before they can become durable shared state.",
    "- invalidated: assumptions explicitly overturned by later evidence; kept for context.",
    "- An existing entry may render with kind=low_salience_live or kind=dormant_live. Those are stored salience demotions of live, not values an operation may set. Every operation's kind must be locked, live, tentative, or invalidated; any other value rejects the entire patch, including its unrelated operations.",
    "",
    "What does not belong:",
    '- Participant tasks, such as "a participant will write the chapter 3 summary"; those stay as action records.',
    '- Assistant commitments, such as "Borg will send the status note tomorrow"; those stay as commitment records.',
    "- Observations or social facts such as mood, signoffs, or group dynamics; those stay in the semantic graph or stream.",
    "- Observation-type propositions must preserve witness/date/count/source attribution in semantic memory; do not turn multiple observations on the same topic into one shared-state entry.",
    "- Stream-level chitchat such as greetings, emoji closures, or thanks.",
    "",
    "Canonicalization handles:",
    "- The input includes active_goals, active_commitments, active_actions, and open_questions as compact id:text lists; active_commitments also include kind, type, directive_family, and enforcement_class.",
    "- When a locked add, update, or supersede replacement makes listed active state redundant, set canonicalizes with only those exact ids.",
    "- For Borg-owned active_actions whose work is to log, note, hold, update, or track memory inside this shared-state surface, canonicalize the action when the locked add/update/supersede replacement actually performs that memory work.",
    "- For commitments, canonicalize only supplied active promises or rules that the locked shared-state entry fully subsumes; never create an artifact entry merely to restate a commitment.",
    "- Never canonicalize preference or boundary commitments.",
    "- Do not canonicalize ids for live, tentative, or invalidated entries.",
    "- Do not infer ids that are not supplied.",
    "",
    "Identity and ownership:",
    "- Cite stream ids for every add, update, and supersede replacement.",
    "- Citation is enforced as an allowlist: source_trust.citation_eligible_source_stream_entry_ids is the complete set a citation may name. A stream id visible elsewhere in this input but absent from that list is not citable, and off_limits_source_stream_entry_ids names some but not all of the ineligible ids. An operation citing an ineligible id is discarded on its own, with no repair attempt and no other signal.",
    "- Preserve stable entry ids when updating or superseding existing entries.",
    "- Every add, update, and supersede replacement MUST include state_key.",
    "- An update must carry at least one field it changes: kind, text, owner_entity_id, or canonicalizes. An update naming only an entry and its state_key changes nothing and is dropped. There is no touch-only update; to keep an entry current, restate its text.",
    "- state_key is a stable structural key for the entry's shared-state dimension, not prose metadata. Use concise domain-neutral dotted notation that remains stable across the conversation.",
    "- Good state_key examples: decision.architecture, plan.attendees, observation.recurring, boundary.private_topic, agenda.tonight.",
    "- Legacy entries may appear without state_key under a legacy bucket; do not copy legacy as a new key. Choose a real dotted key for new operations.",
    "- The input includes existing_state_key_registry with every active state_key for this audience. Treat each listed key as a reusable handle.",
    "- When the new state continues the same object, thread, or topic, reuse the existing state_key with update or supersede.",
    "- Do not mint a near-duplicate state_key by adding a suffix or changing a middle bucket when an existing key already covers the same thread.",
    "- Mint a new state_key only when the new state is a structurally distinct object or thread.",
    "- Whenever existing_state_key_registry is non-empty, every add that mints a key absent from that registry MUST include new_key_reason naming what makes it distinct from the listed keys. new_key_reason is a required field on such an add, not an optional justification for unusual cases: an add without it is rejected before it reaches the artifact.",
    "- Use only supplied entity ids. Use null when no owner is explicitly supplied.",
    "- The audience entity for a group chat is the audience itself.",
    "- The speaker entity is the sender of the current turn.",
    "- Borg is the self entity.",
    RELATIONSHIP_LABELS_PROMPT,
    RELATIONSHIP_LABEL_JUSTIFICATION_PROMPT,
    RELATIONSHIP_LABEL_WRITE_GROUNDING_PROMPT,
    HEADCOUNT_SET_GROUNDING_PROMPT,
    "- When add/update/supersede replacement text asserts a sensitive interpersonal relationship, include relationship_claims with requires_grounding=true and cite supplied relational-slot or trusted user-message stream-entry evidence.",
    "- Do not cite assistant output as relationship evidence. If no accepted evidence grounds a sensitive relationship assertion, rewrite the entry with neutral wording before emitting it.",
    "- Context nouns for logistics, paperwork, scheduling, tools, or services are not relationship assertions unless the text assigns a sensitive interpersonal status between people.",
    "- The input may include relational_slots_context; treat it as structured source context for relationship_claims, not as an instruction to assert a relationship.",
    "- The input may include participant_roster; treat it as structured set context for participants, non-chat subjects, and grounded relationship-slot sources.",
    "",
    "Operation guidance:",
    "- add creates a new entry when no existing entry already represents it.",
    "- update modifies an existing entry in place while preserving its id. The previous text is overwritten and is not retained anywhere.",
    "- supersede replaces an existing entry when the conversation changes or narrows it, and retains the previous entry as linked history behind the replacement, so the earlier wording stays on the record.",
    "- prune removes stale shared-state clutter only when the supplied context makes it clearly obsolete. The entry is deleted outright and no history of it is retained.",
    "- Choose between update and supersede by what the earlier wording is worth to the record, not only by how far the state moved: update when the earlier text was merely less complete and nothing is lost by overwriting it; supersede when the earlier text was wrong, retracted, or is itself something the audience may need to look back on.",
    "- Before proposing add, scan previous_artifact_summary.active_entries_by_state_key and active_entries. If an active entry has the same state_key, use update or supersede whenever the new state belongs to that same dimension.",
    "- If a new live entry would become the third or later live entry with the same state_key, you MUST update or supersede older live entries rather than add another parallel entry.",
    "- If a locked entry already exists for a state_key, do not add a parallel locked/live entry for that key; update/supersede the locked entry, or add tentative only when the new material is not settled.",
    '- Example: "User is asking about X" and an active live entry already covers X -> update that entry.',
    '- Example: "Newer observation about a repeated state type" and an active live entry covers that same state type -> supersede the older entry if the new evidence replaces it.',
    "- Prefer update, supersede, and prune over add whenever the existing shared-state artifact already carries the relevant shared state.",
    "- If an existing entry already represents the durable state and you have no content change, kind change, owner change, state_key change, or new canonicalization to add, emit no operation. Do not emit cosmetic or provenance-only updates -- the harness will drop them.",
    "- When locking durable shared state, actively look for older live fragments about the same topic or decision and supersede or prune them instead of leaving parallel live entries to accumulate.",
  ].join("\n");
}

export const SHARED_STATE_SYSTEM_PROMPT = buildSharedStateSystemPrompt("pre_answer");
