// Borg -- public library entry point.
// Re-exports the stable library surface; implementation modules stay
// behind internal paths.

export const VERSION = "0.1.0";

export {
  Borg,
  type BorgEnqueueMessageInput,
  type BorgEnqueueMessageResult,
  type BorgDreamOptions,
  type BorgDreamRunner,
  type BorgEpisodeGetOptions,
  type BorgEpisodeSearchOptions,
  type BorgOpenOptions,
} from "./borg.js";
export { BorgPool, type BorgPoolOptions } from "./borg/pool.js";
export type {
  BorgActionsFacade,
  BorgAttachmentBytesResult,
  BorgAttachmentMetadataResult,
  BorgAttachmentsFacade,
  BorgAuditFacade,
  BorgAutonomyFacade,
  BorgCommitmentsFacade,
  BorgCorrectionFacade,
  BorgCreatorDirectivesFacade,
  BorgDreamFacade,
  BorgEntitiesFacade,
  BorgEpisodicFacade,
  BorgFacades,
  BorgIdentityFacade,
  BorgInboxCatchUpController,
  BorgInboxCatchUpDrainResult,
  BorgInboxFacade,
  BorgMaintenanceFacade,
  BorgMoodFacade,
  BorgAssembledFramingPromptPreview,
  BorgPromptBlockView,
  BorgPromptsFacade,
  BorgRelationalSlotsFacade,
  BorgReviewFacade,
  BorgReviewResolutionInput,
  BorgSelfFacade,
  BorgSemanticEdgeWithDisclosure,
  BorgSemanticFacade,
  BorgSemanticNodeListResultWithDisclosure,
  BorgSemanticNodeSearchCandidateWithDisclosure,
  BorgSemanticNodeWithDisclosure,
  BorgSemanticWalkStepWithDisclosure,
  BorgSessionsFacade,
  BorgSharedStateFacade,
  BorgSkillsFacade,
  BorgSocialFacade,
  BorgStreamFacade,
  BorgWorkmemFacade,
} from "./borg/public-facade.js";
export { PROMPT_KEYS, type PromptKey } from "./cognition/prompts/registry.js";
export {
  CompositeTracer,
  CallbackTracer,
  JsonlTracer,
  NOOP_TRACER,
  NoopTracer,
  compositeTracer,
  createTurnTracer,
  type CallbackTraceEntry,
  type CallbackTracerOptions,
  type CreateTurnTracerOptions,
  type JsonlTracerOptions,
  type TurnTraceData,
  type TurnTraceEventName,
  type TurnTerminalOutcome,
  type TurnTracer,
} from "./tracing/tracer.js";
export {
  CONVERSATION_KINDS,
  SESSION_AUDIENCE_ROLES,
  SESSION_PRIVACY_LEVELS,
  SESSION_PARTICIPATION_POLICIES,
  SESSION_SOURCE_TYPES,
  SESSION_STATUSES,
  conversationKindSchema,
  sessionAudienceRoleSchema,
  sessionEnsureInputSchema,
  sessionListOptionsSchema,
  sessionParticipationPolicySchema,
  sessionPrivacyLevelSchema,
  sessionQueryOptionsSchema,
  sessionRecordSchema,
  sessionSourceTypeSchema,
  sessionStatusSchema,
  sessionTouchUpdateSchema,
  type ConversationKind,
  type SessionAudienceRole,
  type SessionEnsureInput,
  type SessionListOptions,
  type SessionParticipationPolicy,
  type SessionPrivacyLevel,
  type SessionQueryOptions,
  type SessionRecord,
  type SessionSourceType,
  type SessionStatus,
  type SessionTouchUpdate,
} from "./sessions/index.js";
export {
  PROACTIVE_OUTBOUND_CREATOR_DIRECTIVE_TOPIC_TAG,
  DemoMessageConnector,
  type AutonomousOutboundAuthorizationKind,
  type AutonomousOutboundPromptContext,
  type AutonomousOutboundPromptTarget,
  type MessageConnector,
  type OutboundConnectorDeliverInput,
  type OutboundConnectorDeliverResult,
  type OutboundDeliveryResult,
  type OutboundDeliveryStatus,
  type OutboundMessage,
} from "./outbound/index.js";
export {
  DEFAULT_CONFIG,
  loadConfig,
  postGenerationGuardModeSchema,
  redactConfig,
  type Config,
  type LoadConfigOptions,
  type PostGenerationGuardMode,
} from "./config/index.js";
export {
  FakeEmbeddingClient,
  OpenAICompatibleEmbeddingClient,
  type EmbeddingClient,
  type OpenAICompatibleEmbeddingClientOptions,
} from "./embeddings/index.js";
export {
  AnthropicLLMClient,
  OpenAICompatibleLLMClient,
  type OpenAICompatibleLLMClientOptions,
  type OpenAIChatCompletionsClient,
  LLMStructuredOutputParseError,
  toStructuredOutputFormat,
  type AnthropicAuthMode,
  type AnthropicLLMClientOptions,
  type LLMClient,
  type LLMCacheControl,
  type LLMContentBlock,
  type LLMContentBlockMessage,
  type LLMCompleteOptions,
  type LLMCompleteResult,
  type LLMConverseOptions,
  type LLMConverseResult,
  type LLMMessage,
  type LLMImageRefBlock,
  type LLMOutputConfig,
  type LLMSystemBlock,
  type LLMTextBlock,
  type LLMToolCall,
  type LLMToolDefinition,
  type LLMToolResultBlock,
  type LLMToolUseBlock,
  type TokenUsageEvent,
  type TokenUsageSink,
} from "./llm/index.js";

export {
  ACTION_CANDIDATE_CLASSIFICATIONS,
  COGNITIVE_MODES,
  TURN_ORIGINS,
  FINALIZER_NO_OUTPUT_CATEGORIES,
  FINALIZER_NO_OUTPUT_SEMANTIC_CATEGORIES,
  FINALIZER_NO_OUTPUT_STRUCTURAL_CATEGORIES,
  FRAME_ANOMALY_KINDS,
  GOAL_PROMOTION_CLASSIFICATIONS,
  actionCandidateClassificationSchema,
  goalPromotionClassificationSchema,
  evidenceLedgerSourceTypeSchema,
  classifySuppressionReason,
  isFrameAnomaly,
  isMinimalUserGenerationInput,
  type AttentionWeights,
  type ActionCandidateClassification,
  type CognitiveMode,
  type GenerationSuppressionReason,
  type EmissionRecommendation,
  type FinalizerNoOutputCategory,
  type FinalizerNoOutputPrimaryReason,
  type FinalizerNoOutputSemanticCategory,
  type FinalizerNoOutputStructuralCategory,
  type FinalizerNoOutputStructuralFlag,
  type GoalPromotionClassification,
  type SuppressionOutcomeClass,
  type ActualFrameAnomalyClassification,
  type ClassifyFrameAnomalyInput,
  type EvidenceLedger,
  type EvidenceLedgerActor,
  type EvidenceLedgerEntry,
  type EvidenceLedgerSection,
  type EvidenceLedgerSectionId,
  type EvidenceLedgerSessionScope,
  type EvidenceLedgerSourceType,
  type EvidenceLedgerTaint,
  type EvidenceLedgerTraceSummary,
  type EvidenceLedgerTranscriptOmittedReason,
  type EvidenceLedgerImageAttachment,
  type FrameAnomalyClassification,
  type FrameAnomalyKind,
  type IntentRecord,
  type MessageDiscourseControl,
  type ParticipantRoster,
  type ParticipantRosterMember,
  type ParticipantRosterStreamEvidence,
  type ParticipantRosterSubject,
  type ParticipantRosterUncertain,
  type PerceptionResult,
  type PendingTurnEmission,
  type ReplyTarget,
  type TemporalCue,
  type TurnEmission,
  type ToolLoopCallRecord,
  type TurnInput,
  type TurnOrigin,
  type TurnResult,
  type TurnStakes,
} from "./cognition/index.js";
export {
  AUTONOMY_CONDITION_NAMES,
  AUTONOMY_TRIGGER_NAMES,
  AUTONOMY_WAKE_SOURCE_METADATA,
  AUTONOMY_WAKE_SOURCE_NAMES,
  type AutonomyConditionName,
  type AutonomySchedulerBudgetDescription,
  type AutonomySchedulerConditionSourceDescription,
  type AutonomySchedulerDescription,
  type AutonomySchedulerSourceDescription,
  type AutonomySchedulerTriggerSourceDescription,
  type AutonomySchedulerWakeGroupDescription,
  type AutonomyTickEventResult,
  type AutonomyWakeRecord,
  type AutonomyWakeRecordInput,
  type AutonomyWakeSourceCategory,
  type AutonomyWakeSourceName,
  type AutonomyWakeSourceType,
  type DueEvent,
  type TickResult,
} from "./autonomy/index.js";
export {
  type ExecutiveFocus,
  type ExecutiveGoalScore,
  type ExecutiveGoalScoreComponents,
  type ExecutiveStep,
  type ExecutiveStepAddInput,
  type ExecutiveStepKind,
  type ExecutiveStepPatch,
  type ExecutiveStepStatus,
} from "./executive/index.js";
export {
  OFFLINE_PROCESS_NAMES,
  type MaintenanceAuditRecord,
  type MaintenanceCadence,
  type MaintenancePlan,
  type MaintenanceSchedulerObserver,
  type MaintenanceSchedulerStopOptions,
  type MaintenanceTickResult,
  type OfflineChange,
  type OfflineMaintenanceProcessPlan,
  type OfflineProcessError,
  type OfflineProcessName,
  type OfflineProcessPlan,
  type OfflineResult,
  type OrchestratorResult,
  type ReviewRevalidationOptions,
  type ReviewRevalidationResult,
} from "./offline/index.js";

export { type Provenance, type ProvenanceKind } from "./memory/common/index.js";
export {
  type AffectiveSignal as MemoryAffectiveSignal,
  type DominantEmotion,
  type EmotionalArc,
  type MoodHistoryEntry,
  type MoodState,
} from "./memory/affective/index.js";
export {
  ACTION_SESSION_SCOPES,
  ACTION_STATES,
  type ActionAddOptions,
  type ActionActor,
  type ActionCountByState,
  type ActionCreationCountsBySource,
  type ActionRecord,
  type ActionRecordCreationSource,
  type ActionRecordListFilter,
  type ActionRecordPatch,
  type ActionSessionScope,
  type ActionState,
} from "./memory/actions/index.js";
export {
  RELATIONAL_SLOT_STATES,
  type RelationalSlot,
  type RelationalSlotAlternateValue,
  type RelationalSlotAssertion,
  type RelationalSlotAssertionConfirmation,
  type RelationalSlotCountByState,
  type RelationalSlotNegation,
  type RelationalSlotState,
} from "./memory/relational-slots/index.js";
export {
  EPISODE_TIERS,
  type Episode,
  type EpisodeListOptions,
  type EpisodeListResult,
  type EpisodePatch,
  type EpisodeSearchCandidate,
  type EpisodeSearchOptions,
  type EpisodeStats,
  type EpisodeStatsPatch,
  type EpisodeTier,
  type ExtractFromStreamResult,
} from "./memory/episodic/index.js";
export {
  IDENTITY_RECORD_TYPES,
  type IdentityEvent,
  type IdentityRecordType,
  type IdentityUpdateOptions,
  type IdentityUpdateResult,
} from "./memory/identity/index.js";
export {
  deriveProceduralContextKey,
  type SkillRecord,
  type ProceduralContext,
  type ProceduralContextAudienceScope,
  type ProceduralContextProblemKind,
  type SkillContextStatsRecord,
  type SkillSearchCandidate,
  type SkillSelectionCandidate,
  type SkillSelectionResult,
  type SkillStats,
} from "./memory/procedural/index.js";
export {
  GROWTH_MARKER_CATEGORIES,
  OPEN_QUESTION_SOURCES,
  OPEN_QUESTION_STATUSES,
  type AutobiographicalPeriod,
  type AutobiographicalPeriodPatch,
  type GoalPatch,
  type GoalRecord,
  type GoalStatus,
  type GoalTreeNode,
  type GrowthMarker,
  type GrowthMarkerCategory,
  type GrowthMarkerPatch,
  type GrowthMarkersSummary,
  type OpenQuestion,
  type OpenQuestionGoalLookupOptions,
  type OpenQuestionHandleLookupOptions,
  type OpenQuestionListOptions,
  type OpenQuestionPatch,
  type OpenQuestionSearchCandidate,
  type OpenQuestionSimilarLookupOptions,
  type OpenQuestionSource,
  type OpenQuestionStatus,
  type TraitPatch,
  type TraitRecord,
  type ValuePatch,
  type ValueRecord,
} from "./memory/self/index.js";
export {
  type SocialEvent,
  type SocialProfile,
  type SocialSentimentPoint,
} from "./memory/social/index.js";
export {
  BORG_ROLES,
  COMMITMENT_CRITICAL_DOMAINS,
  COMMITMENT_ENFORCEMENT_CLASSES,
  COMMITMENT_KINDS,
  COMMITMENT_TYPES,
  effectiveCommitmentCriticalDomain,
  effectiveCommitmentEnforcementClass,
  borgRoleSchema,
  type BorgRole,
  type CommitmentCriticalDomain,
  type CommitmentEnforcementClass,
  type CommitmentRecord,
  type CommitmentPatch,
  type CommitmentKind,
  type CommitmentType,
  type ClosurePressureRelevance,
  type EntityKind,
  type EntityRecord,
  type NameProvenance,
} from "./memory/commitments/index.js";
export {
  CREATOR_DIRECTIVE_ACTIVATION_REASONS,
  CREATOR_DIRECTIVE_ACTIVATION_SCOPES,
  CREATOR_DIRECTIVE_CONTENT_SCOPES,
  CREATOR_DIRECTIVE_DENIED_AUDIENCE_BEHAVIORS,
  CREATOR_DIRECTIVE_KINDS,
  CREATOR_DIRECTIVE_MENTION_POLICIES,
  CREATOR_DIRECTIVE_RENDER_REASONS,
  CREATOR_DIRECTIVE_RENDER_MODES,
  CREATOR_DIRECTIVE_SEMANTIC_SLOTS,
  CREATOR_DIRECTIVE_STATUSES,
  CREATOR_DIRECTIVE_SUBJECT_KINDS,
  activationPolicySchema,
  creatorDirectiveApplicableOptionsSchema,
  creatorDirectiveActivationReasonSchema,
  creatorDirectiveActivationScopeSchema,
  creatorDirectiveContentScopeSchema,
  creatorDirectiveDeniedAudienceBehaviorSchema,
  creatorDirectiveEntityIdSchema,
  creatorDirectiveIdSchema,
  creatorDirectiveKindSchema,
  creatorDirectiveListFilterSchema,
  creatorDirectiveMentionPolicySchema,
  creatorDirectiveQueueInputSchema,
  creatorDirectiveRenderModeSchema,
  creatorDirectiveRenderReasonSchema,
  creatorDirectiveSchema,
  creatorDirectiveSemanticSlotSchema,
  creatorDirectiveSessionIdSchema,
  creatorDirectiveStatusSchema,
  creatorDirectiveStreamEntryIdSchema,
  creatorDirectiveSubjectKindSchema,
  creatorDirectiveTopicTagSchema,
  disclosurePolicySchema,
  type ActivationPolicy,
  type CreatorDirective,
  type CreatorDirectiveActivationReason,
  type CreatorDirectiveActivationScope,
  type CreatorDirectiveApplicable,
  type CreatorDirectiveApplicableOptions,
  type CreatorDirectiveContentScope,
  type CreatorDirectiveDeniedAudienceBehavior,
  type CreatorDirectiveKind,
  type CreatorDirectiveListFilter,
  type CreatorDirectiveMentionPolicy,
  type CreatorDirectiveQueueInput,
  type CreatorDirectiveRenderMode,
  type CreatorDirectiveRenderReason,
  type CreatorDirectiveSemanticSlot,
  type CreatorDirectiveStatus,
  type CreatorDirectiveSubjectKind,
  type DisclosurePolicy,
} from "./memory/creator-directives/index.js";
export {
  SEMANTIC_NODE_STATUSES,
  semanticEdgeIdSchema,
  semanticNodeIdSchema,
  type ExtractSemanticResult,
  type SemanticContext,
  type SemanticEdge,
  type SemanticEdgeListOptions,
  type SemanticEdgePatch,
  type SemanticNode,
  type SemanticNodeKind,
  type SemanticNodeListOptions,
  type SemanticNodePatch,
  type SemanticNodeSearchCandidate,
  type SemanticNodeSearchOptions,
  type SemanticNodeStatus,
  type SemanticRelation,
  type SemanticWalkOptions,
  type SemanticWalkStep,
} from "./memory/semantic/index.js";
export {
  REVIEW_KINDS,
  REVIEW_RESOLUTIONS,
  creatorDirectiveReconciliationReviewRefsSchema,
  type ReviewKind,
  type ReviewQueueItem,
  type ReviewResolution,
  type ReviewResolutionInput,
  type StoredReviewKind,
} from "./memory/review-queue/index.js";
export { type WorkingMemory } from "./memory/working/index.js";
export { normalizeEpisodeAccess, type EpisodeAccessLike } from "./memory/episodic/index.js";
export {
  ACTIVE_SHARED_STATE_ENTRY_KINDS,
  CANONICAL_SHARED_STATE_ENTRY_KINDS,
  DEMOTED_LIVE_SHARED_STATE_ENTRY_KINDS,
  SHARED_STATE_ENTRY_KINDS,
  type SharedStateArtifact,
  type SharedStateCanonicalizes,
  type SharedStateEntry,
  type SharedStateEntryKind,
  type SharedStateSourceTrustRejectionReason,
  type SharedStateSourceTrustResult,
} from "./memory/shared-state/index.js";

export {
  MEMORY_DISCLOSURE_CLASSES,
  SELF_RECALL_SCOPE,
  memoryDisclosureLabelFromEpisodeAccess,
  memoryDisclosureLabelMetadata,
  type CognitionRecallContext,
  type DisclosureContext,
  type EvidenceItem,
  type EvidencePool,
  type MemoryDisclosureClass,
  type MemoryDisclosureLabel,
  type MemoryDisclosureLabelMetadata,
  type RecallEvidenceHandle,
  type RecallIntent,
  type RetrievedContext,
  type RetrievedContradictionRouting,
  type RetrievedContradictionRoutingItem,
  type RetrievedContradictionSessionScope,
  type RetrievedEpisode,
  type RetrievedSemantic,
  type RetrievedSemanticHit,
  type RetrievedSemanticNode,
  type RetrievedSemanticUnderReview,
  type RetrievalConfidence,
  type CognitionRetrievalOptions,
  type DisclosureRetrievalOptions,
  type RetrievalGetEpisodeOptions,
  type RetrievalSharedOptions,
  type RetrievalSearchOptions,
} from "./retrieval/index.js";
export {
  NARRATIVE_STREAM_ENTRY_KINDS,
  QUARANTINED_USER_ENTRY_EVENT,
  STREAM_ENTRY_KINDS,
  STREAM_ENTRY_PERSISTENCE_CLASSES,
  isNarrativeStreamEntry,
  streamCursorSchema,
  streamEntryPersistenceClassSchema,
  streamResponseToSchema,
  streamSourceMessageKeySchema,
  type StreamCursor,
  type StreamEntry,
  type StreamEntryInput,
  type StreamEntryKind,
  type StreamEntryPersistenceClass,
  type StreamResponseTo,
  type StreamSourceMessageKey,
  type NarrativeStreamEntryKind,
  type StreamIterateOptions,
} from "./stream/index.js";

export { FixedClock, ManualClock, SystemClock, type Clock } from "./util/clock.js";
export {
  AuthError,
  AttachmentError,
  AutonomyError,
  BorgError,
  BudgetExceededError,
  CognitionError,
  CommitmentError,
  ConfigError,
  EmbeddingError,
  IdentityCasMismatchError,
  LLMError,
  ProvenanceError,
  RetrievalError,
  SemanticError,
  SessionBusyError,
  StorageError,
  StreamError,
  ToolError,
  WorkingMemoryError,
  type AttachmentErrorCode,
  type AuthErrorCode,
  type BorgDefaultErrorCode,
  type BorgErrorCode,
  type BorgErrorJSON,
  type BorgErrorOptions,
  type BorgTypedErrorOptions,
  type ConfigErrorCode,
  type KnownBorgErrorCode,
  type LLMErrorCode,
  type StorageErrorCode,
  type StreamErrorCode,
} from "./util/errors.js";
export {
  DEFAULT_SESSION_ID,
  createActionId,
  createAttachmentId,
  createAutobiographicalPeriodId,
  createAutonomyWakeId,
  createCommitmentId,
  createCreatorDirectiveId,
  createEntityId,
  createEpisodeId,
  createExecutiveStepId,
  createGoalId,
  createGrowthMarkerId,
  createMaintenanceRunId,
  createOpenQuestionId,
  createProceduralEvidenceId,
  createRelationalSlotId,
  createSemanticEdgeId,
  createSemanticNodeId,
  createSessionId,
  createSharedStateEntryId,
  createSkillId,
  createStreamEntryId,
  createTraitId,
  createValueId,
  parseActionId,
  parseAutobiographicalPeriodId,
  parseAutonomyWakeId,
  parseCommitmentId,
  parseCreatorDirectiveId,
  parseEntityId,
  parseEpisodeId,
  parseSessionId,
  parseExecutiveStepId,
  parseGoalId,
  parseGrowthMarkerId,
  parseMaintenanceRunId,
  parseOpenQuestionId,
  parseProceduralEvidenceId,
  parseRelationalSlotId,
  parseSemanticEdgeId,
  parseSemanticNodeId,
  parseSharedStateEntryId,
  parseSkillId,
  parseStreamEntryId,
  parseTraitId,
  parseValueId,
  type ActionId,
  type AuditId,
  type AttachmentId,
  type AutobiographicalPeriodId,
  type AutonomyWakeId,
  type BrandedId,
  type CommitmentId,
  type CreatorDirectiveId,
  type ExecutiveStepId,
  type EntityId,
  type EpisodeId,
  type GoalId,
  type GrowthMarkerId,
  type MaintenanceRunId,
  type OpenQuestionId,
  type ProceduralEvidenceId,
  type RelationalSlotId,
  type SemanticEdgeId,
  type SemanticNodeId,
  type SessionId,
  type SharedStateEntryId,
  type SkillId,
  type StreamEntryId,
  type TraitId,
  type ValueId,
} from "./util/ids.js";
export {
  type BorgUserContentBlock,
  type ImagePerceptionRecord,
  type ImageMediaType,
  type StoredAttachmentRecord,
  type TurnInputAttachment,
} from "./attachments/index.js";

// Akuki-specific wiring, exported for the connector package that lives outside
// this repository. Upstream borg has no reason to expose these; this fork does,
// because the BotArena transport is platform code and belongs in its own package
// (the same split sol-connector makes), while the seed, the model clients and the
// prediction parameters are entity code and belong here.
export { applyAkukiSeed } from "./akuki/seed/apply.js";
export { applyAkukiTemperamentEnv } from "./akuki/prediction-config.js";
export { buildAkukiClients } from "./akuki/tenant.js";
